from __future__ import annotations

CORPUS = [
    {
        "text_id": "plato_apology",
        "title": "Apology",
        "author": "Plato",
        "tradition": "Greek",
        "period": "Ancient",
        "school": "Platonism",
        "gutenberg_id": 1656,
    },
    {
        "text_id": "plato_crito",
        "title": "Crito",
        "author": "Plato",
        "tradition": "Greek",
        "period": "Ancient",
        "school": "Platonism",
        "gutenberg_id": 1657,
    },
    {
        "text_id": "plato_phaedo",
        "title": "Phaedo",
        "author": "Plato",
        "tradition": "Greek",
        "period": "Ancient",
        "school": "Platonism",
        "gutenberg_id": 1658,
    },
    {
        "text_id": "plato_republic",
        "title": "Republic",
        "author": "Plato",
        "tradition": "Greek",
        "period": "Ancient",
        "school": "Platonism",
        "gutenberg_id": 1497,
    },
    {
        "text_id": "plato_symposium",
        "title": "Symposium",
        "author": "Plato",
        "tradition": "Greek",
        "period": "Ancient",
        "school": "Platonism",
        "gutenberg_id": 1600,
    },
    {
        "text_id": "aristotle_nicomachean_ethics",
        "title": "Nicomachean Ethics",
        "author": "Aristotle",
        "tradition": "Greek",
        "period": "Ancient",
        "school": "Aristotelianism",
        "gutenberg_id": 8438,
    },
    {
        "text_id": "aristotle_politics",
        "title": "Politics",
        "author": "Aristotle",
        "tradition": "Greek",
        "period": "Ancient",
        "school": "Aristotelianism",
        "gutenberg_id": 6762,
    },
    {
        "text_id": "aristotle_poetics",
        "title": "Poetics",
        "author": "Aristotle",
        "tradition": "Greek",
        "period": "Ancient",
        "school": "Aristotelianism",
        "gutenberg_id": 1974,
    },
    {
        "text_id": "epictetus_enchiridion",
        "title": "The Enchiridion",
        "author": "Epictetus",
        "tradition": "Greek",
        "period": "Ancient",
        "school": "Stoicism",
        "gutenberg_id": 45109,
    },
    {
        "text_id": "marcus_aurelius_meditations",
        "title": "Meditations",
        "author": "Marcus Aurelius",
        "tradition": "Roman",
        "period": "Ancient",
        "school": "Stoicism",
        "gutenberg_id": 2680,
    },
    {
        "text_id": "lucretius_on_nature",
        "title": "On the Nature of Things",
        "author": "Lucretius",
        "tradition": "Roman",
        "period": "Ancient",
        "school": "Epicureanism",
        "gutenberg_id": 785,
    },
    {
        "text_id": "confucius_analects",
        "title": "The Analects",
        "author": "Confucius",
        "tradition": "Chinese",
        "period": "Ancient",
        "school": "Confucianism",
        "gutenberg_id": 4094,
    },
    {
        "text_id": "laozi_tao_te_ching",
        "title": "Tao Te Ching",
        "author": "Laozi",
        "tradition": "Chinese",
        "period": "Ancient",
        "school": "Daoism",
        "gutenberg_id": 216,
    },
    {
        "text_id": "dhammapada",
        "title": "The Dhammapada",
        "author": "Anonymous",
        "tradition": "Indian",
        "period": "Ancient",
        "school": "Buddhism",
        "gutenberg_id": 2017,
    },
    {
        "text_id": "augustine_confessions",
        "title": "The Confessions",
        "author": "Augustine",
        "tradition": "Christian",
        "period": "Late Antique",
        "school": "Christian philosophy",
        "gutenberg_id": 3296,
    },
    {
        "text_id": "machiavelli_prince",
        "title": "The Prince",
        "author": "Niccolo Machiavelli",
        "tradition": "Italian",
        "period": "Renaissance",
        "school": "Political realism",
        "gutenberg_id": 1232,
    },
    {
        "text_id": "more_utopia",
        "title": "Utopia",
        "author": "Thomas More",
        "tradition": "English",
        "period": "Renaissance",
        "school": "Utopian political thought",
        "gutenberg_id": 2130,
    },
    {
        "text_id": "descartes_discourse_method",
        "title": "Discourse on the Method",
        "author": "Rene Descartes",
        "tradition": "French",
        "period": "Early modern",
        "school": "Rationalism",
        "gutenberg_id": 59,
    },
    {
        "text_id": "descartes_meditations",
        "title": "Meditations on First Philosophy",
        "author": "Rene Descartes",
        "tradition": "French",
        "period": "Early modern",
        "school": "Rationalism",
        "gutenberg_id": 23306,
    },
    {
        "text_id": "spinoza_ethics",
        "title": "Ethics",
        "author": "Baruch Spinoza",
        "tradition": "Dutch",
        "period": "Early modern",
        "school": "Rationalism",
        "gutenberg_id": 3800,
    },
    {
        "text_id": "locke_second_treatise",
        "title": "Second Treatise of Government",
        "author": "John Locke",
        "tradition": "English",
        "period": "Early modern",
        "school": "Liberalism",
        "gutenberg_id": 7370,
    },
    {
        "text_id": "berkeley_principles",
        "title": "A Treatise Concerning the Principles of Human Knowledge",
        "author": "George Berkeley",
        "tradition": "Irish",
        "period": "Early modern",
        "school": "Idealism",
        "gutenberg_id": 4723,
    },
    {
        "text_id": "hume_enquiry",
        "title": "An Enquiry Concerning Human Understanding",
        "author": "David Hume",
        "tradition": "Scottish",
        "period": "Early modern",
        "school": "Empiricism",
        "gutenberg_id": 9662,
    },
    {
        "text_id": "hume_dialogues",
        "title": "Dialogues Concerning Natural Religion",
        "author": "David Hume",
        "tradition": "Scottish",
        "period": "Early modern",
        "school": "Empiricism",
        "gutenberg_id": 4583,
    },
    {
        "text_id": "rousseau_social_contract",
        "title": "The Social Contract and Discourses",
        "author": "Jean-Jacques Rousseau",
        "tradition": "French",
        "period": "Enlightenment",
        "school": "Social contract theory",
        "gutenberg_id": 46333,
    },
    {
        "text_id": "kant_groundwork",
        "title": "Fundamental Principles of the Metaphysic of Morals",
        "author": "Immanuel Kant",
        "tradition": "German",
        "period": "Enlightenment",
        "school": "Kantianism",
        "gutenberg_id": 5682,
    },
    {
        "text_id": "mill_utilitarianism",
        "title": "Utilitarianism",
        "author": "John Stuart Mill",
        "tradition": "English",
        "period": "Modern",
        "school": "Utilitarianism",
        "gutenberg_id": 11224,
    },
    {
        "text_id": "mill_on_liberty",
        "title": "On Liberty",
        "author": "John Stuart Mill",
        "tradition": "English",
        "period": "Modern",
        "school": "Liberalism",
        "gutenberg_id": 34901,
    },
    {
        "text_id": "nietzsche_zarathustra",
        "title": "Thus Spake Zarathustra",
        "author": "Friedrich Nietzsche",
        "tradition": "German",
        "period": "Modern",
        "school": "Existentialism",
        "gutenberg_id": 1998,
    },
    {
        "text_id": "nietzsche_beyond_good_evil",
        "title": "Beyond Good and Evil",
        "author": "Friedrich Nietzsche",
        "tradition": "German",
        "period": "Modern",
        "school": "Existentialism",
        "gutenberg_id": 4363,
    },
    {
        "text_id": "nietzsche_genealogy_morals",
        "title": "The Genealogy of Morals",
        "author": "Friedrich Nietzsche",
        "tradition": "German",
        "period": "Modern",
        "school": "Existentialism",
        "gutenberg_id": 52319,
    },
    {
        "text_id": "william_james_pragmatism",
        "title": "Pragmatism",
        "author": "William James",
        "tradition": "American",
        "period": "Modern",
        "school": "Pragmatism",
        "gutenberg_id": 5116,
    },
]

